### PR TITLE
Renamed local-authority-wls to principal-local-authority

### PR DESCRIPTION
**Pull request by psd**
Updated the maps by hand. 

We need to revisit and replace the tests and report generation.

(note this replaces a previous branch with the same name)

### CODE REVIEW

**Comment by symroe** [comment]
Can you explain the thinking behind "principal" a little?

**Review by Jamie-Atkinson — APPROVED** [review]
thanks paul looks good

**Comment by symroe** [comment]
…I ask because this has quite a few implications for users of the data and it would be nice to understand it a little more.

For example: will the territory code be removed from the other `local-authority` registers? Does this only change for the Welsh ones?

Is this change documented anywhere else? It doesn't seem to have any information at all on the [history page](https://registers.cloudapps.digital/registers/local-authority-wls), and the commits to this repo don't explain it either.

**Comment by psd** [comment]
Hi Sym

I think I understand your concerns, and sense you're expecting the four local authority registers to be the same shape, which may not be the case. We much prefer each register to record the data as understood and managed by each custodian, rather than becoming a wrong abstraction. I think this might be something for us to explain and address more formally during alpha which should be after the elections when we can publicise work in progress.

I'm sorry the git history of wranging the data doesn't explain the rationale behind the decision to rename the register. We need to update the history page to reflect discussions with the custodian which led to the name change.

The data in this repository had territories, but these aren't in the beta/alpha https://local-authority-eng.register.gov.uk/, https://local-authority-sct.alpha.openregister.org/ registers.

Paul

**Pull request merged**
